import json
import os

JSON_SOURCE = '../StormsRulebook2026/storms_power_master_v3_1.json'
WEB_APP_DEST = './src/data/allAbilities.ts'

CLASS_JSON_SOURCE = '../StormsRulebook2026/storms_class_master_v3_1.json'
CLASS_WEB_APP_DEST = './src/data/classData.ts'

def export():
    print(f"Reading from: {os.path.abspath(JSON_SOURCE)}")

    if not os.path.exists(JSON_SOURCE):
        print(f"❌ Error: Could not find the JSON file at {JSON_SOURCE}")
        return

    with open(JSON_SOURCE, 'r') as f:
        abilities = json.load(f)

    ts_header = """// AUTO-GENERATED BY export_to_web.py - DO NOT EDIT MANUALLY
export interface Ability {
  powerId: string;
  weight: number;         
  name: string;
  abilityType: string;
  frequency: string;
  power: string;
  charge: boolean;
  school: string;
  abilityRange: string;
  incantation: string | null;
  material: string | null;
  effect: string;
  note: string | null;
  limitation: string | null;
  reference: string[];    
  incantation_multiplier: number;
  inactive: boolean;
  terrain: boolean;
}

export const ALL_ABILITIES: Ability[] = """

    with open(CLASS_JSON_SOURCE, 'r') as f:
        class_data = json.load(f)

    ts_class_content = f"// AUTO-GENERATED\nexport const CLASS_DATA = {json.dumps(class_data, indent=2)};"

    with open(CLASS_WEB_APP_DEST, 'w') as f:
        f.write(ts_class_content)

    for ability in abilities:
        if 'terrain' not in ability:
            ability['terrain'] = False

    for ability in abilities:
        if 'inactive' not in ability:
            ability['inactive'] = False

    ts_data = json.dumps(abilities, indent=2)
    full_content = f"{ts_header}{ts_data};\n"

    os.makedirs(os.path.dirname(WEB_APP_DEST), exist_ok=True)
    with open(WEB_APP_DEST, 'w') as f:
        f.write(full_content)

    print(f"✅ Success! {len(abilities)} abilities exported to {WEB_APP_DEST}")

if __name__ == "__main__":
    export()