import json
import os
import re

# --- CONFIGURATION ---
POWER_MASTER = '../StormsRulebook2026/storms_power_master_v3_1.json'
CLASS_MASTER = '../StormsRulebook2026/storms_class_master_v3_1.json'
WEB_POWER_DEST = './src/data/allPowers.ts'
WEB_CLASS_DEST = './src/data/classData.ts'

def extract_limit(limitation_text):
    if not limitation_text: return None
    text = limitation_text.lower()
    if "once" in text: return 1
    if "twice" in text: return 2
    if "thrice" in text: return 3
    return None

def export():
    with open(POWER_MASTER, 'r') as f:
        power_library = json.load(f)
    with open(CLASS_MASTER, 'r') as f:
        class_master = json.load(f)

    power_lookup = {p['powerId']: p for p in power_library}
    all_powers_output = []
    
    # Clone master to update IDs for the web export
    web_class_data = json.loads(json.dumps(class_master))

    for class_name, class_data in web_class_data['classes'].items():
        is_martial = class_data.get('ruleSet') == 'martial'
        
        for mapping in class_data.get('tierMapping', []):
            original_id = mapping['powerId']
            namespaced_id = f"{class_name.lower()}_{original_id}"
            mapping['powerId'] = namespaced_id
            
            tier = mapping['level']
            source = power_lookup.get(original_id)
            if not source: continue

            # --- COST LOGIC ---
            is_archetype = source.get('abilityType') == 'Archetype'
            origin = source.get('power', 'A')
            
            cost = 1
            if tier == 0 or str(tier) == '0':
                cost = 0
            elif is_archetype:
                cost = 2
            elif is_martial or origin == 'T':
                cost = 0

            power_entry = {
                "id": namespaced_id,
                "originalId": original_id,
                "className": class_name,
                "name": source.get('name', 'Unknown'),
                "tier": int(tier) if str(tier).isdigit() else 0,
                "origin": origin,
                "cost": cost, 
                "freq_multiplier": 1,
                "arch_restrict": False,
                "isReference": (str(tier) == '0'),
                "purchase_limit": source.get('purchase_limit') or extract_limit(source.get('limitation')),
                
                # Mapped to new field names
                "type": source.get('abilityType'),
                "frequency": source.get('frequency'),
                "charge": source.get('charge', False),
                "school": source.get('school'),
                "range": source.get('abilityRange'),
                "incantation": source.get('incantation'),
                "material": source.get('material'),
                "effect": source.get('effect'),
                "note": source.get('note'),
                "limitation": source.get('limitation'),
                "reference": source.get('reference', []),
                "incantation_multiplier": source.get('incantation_multiplier', 1),
                "terrain": source.get('terrain', False),
                "inactive": source.get('inactive', False),
                "weight": source.get('weight', 10)
            }
            all_powers_output.append(power_entry)

    # --- WRITE ALL_POWERS ---
    ts_power_header = """// AUTO-GENERATED BY export_to_web.py - DO NOT EDIT MANUALLY
export interface Power {
  id: string;
  originalId: string;
  className: string;
  name: string;
  tier: number;
  origin: 'S' | 'A' | 'T';
  cost: number;
  freq_multiplier: number;
  arch_restrict: boolean;
  isReference: boolean;
  purchase_limit: number | null;
  type: string;
  frequency: string;
  charge: boolean;
  school: string;
  range: string;
  incantation: string | null;
  material: string | null;
  effect: string;
  note: string | null;
  limitation: string | null;
  reference: string[];
  incantation_multiplier: number;
  terrain: boolean;
  inactive: boolean;
  weight: number;
}

export const ALL_POWERS: Power[] = """

    with open(WEB_POWER_DEST, 'w') as f:
        f.write(ts_power_header + json.dumps(all_powers_output, indent=2) + ";")

    # --- WRITE CLASS_DATA ---
    ts_class_header = """// AUTO-GENERATED BY export_to_web.py - DO NOT EDIT MANUALLY
export const CLASS_DATA = """

    with open(WEB_CLASS_DEST, 'w') as f:
        f.write(ts_class_header + json.dumps(web_class_data, indent=2) + ";")

    print(f"✅ Success! Exported {len(all_powers_output)} Power entries with updated field names.")

if __name__ == "__main__":
    export()