// AUTO-GENERATED BY export_to_web.py - DO NOT EDIT MANUALLY
export const CLASS_DATA = {
  "globalRules": {
    "caster": "Caster classes purchase Powers from a list of options. Players have three points per Level they are playing. Powers may be purchased multiple times, and cost one point with the exception of Archetypes. Unused points from higher levels may be used on lower levels.  A list of all purchased Powers should be carried while playing.",
    "martial": "Martial classes gain a static list of Powers corresponding to their level. Players gain all Powers at each level with the exception of Archetypes, which are optional. Players may choose up to one Archetype at level five."
  },
  "classes": {
    "Barbarian": {
      "className": "Barbarian",
      "ruleSet": "martial",
      "tierMapping": [
        {
          "powerId": "barbarian_a_adrenaline",
          "powerName": "Adrenaline",
          "level": 1
        },
        {
          "powerId": "barbarian_t_unstoppable",
          "powerName": "Unstoppable",
          "level": 1
        },
        {
          "powerId": "barbarian_a_fight_after_death",
          "powerName": "Fight After Death",
          "level": 2
        },
        {
          "powerId": "barbarian_t_light_armor",
          "powerName": "Light Armor",
          "level": 3
        },
        {
          "powerId": "barbarian_t_martial_feat",
          "powerName": "Martial Feat",
          "level": 3
        },
        {
          "powerId": "barbarian_s_fire_bolt",
          "powerName": "Fire Bolt",
          "level": 0
        },
        {
          "powerId": "barbarian_t_too_angry_to_die",
          "powerName": "Too Angry To Die",
          "level": 4
        },
        {
          "powerId": "barbarian_t_battleborn",
          "powerName": "Battleborn",
          "level": 5
        },
        {
          "powerId": "barbarian_a_blood_and_thunder",
          "powerName": "Blood and Thunder",
          "level": 0
        },
        {
          "powerId": "barbarian_t_berserker",
          "powerName": "Berserker",
          "level": 5
        },
        {
          "powerId": "barbarian_t_storm_the_keep",
          "powerName": "Storm the Keep",
          "level": 1
        }
      ]
    },
    "Bard": {
      "className": "Bard",
      "ruleSet": "caster",
      "tierMapping": [
        {
          "powerId": "bard_t_silver_tongue",
          "powerName": "Silver Tongue",
          "level": 1
        },
        {
          "powerId": "bard_s_charm_person",
          "powerName": "Charm Person",
          "level": 1
        },
        {
          "powerId": "bard_s_mend",
          "powerName": "Mend",
          "level": 1
        },
        {
          "powerId": "bard_s_release",
          "powerName": "Release",
          "level": 1
        },
        {
          "powerId": "bard_s_song_of_parry",
          "powerName": "Song of Parry",
          "level": 1
        },
        {
          "powerId": "bard_t_missile_block",
          "powerName": "Missile Block",
          "level": 0
        },
        {
          "powerId": "bard_s_confidence",
          "powerName": "Confidence",
          "level": 2
        },
        {
          "powerId": "bard_s_hurled_insult",
          "powerName": "Hurled Insult",
          "level": 2
        },
        {
          "powerId": "bard_t_jack_of_all_trades",
          "powerName": "Jack of All Trades",
          "level": 2
        },
        {
          "powerId": "bard_t_light_armor",
          "powerName": "Light Armor",
          "level": 0
        },
        {
          "powerId": "bard_s_rally",
          "powerName": "Rally",
          "level": 2
        },
        {
          "powerId": "bard_s_song_of_brilliance",
          "powerName": "Song of Brilliance",
          "level": 0
        },
        {
          "powerId": "bard_s_fear",
          "powerName": "Fear",
          "level": 3
        },
        {
          "powerId": "bard_s_inspiration",
          "powerName": "Inspiration",
          "level": 3
        },
        {
          "powerId": "bard_t_master_of_none",
          "powerName": "Master of None",
          "level": 3
        },
        {
          "powerId": "bard_t_martial_feat",
          "powerName": "Martial Feat",
          "level": 0
        },
        {
          "powerId": "bard_s_song_of_glamour",
          "powerName": "Song of Glamour",
          "level": 3
        },
        {
          "powerId": "bard_s_pacify",
          "powerName": "Pacify",
          "level": 3
        },
        {
          "powerId": "bard_s_heroism",
          "powerName": "Heroism",
          "level": 4
        },
        {
          "powerId": "bard_s_lost",
          "powerName": "Lost",
          "level": 4
        },
        {
          "powerId": "bard_s_fire_bolt",
          "powerName": "Fire Bolt",
          "level": 0
        },
        {
          "powerId": "bard_s_terror",
          "powerName": "Terror",
          "level": 4
        },
        {
          "powerId": "bard_s_song_of_prowess",
          "powerName": "Song of Prowess",
          "level": 4
        },
        {
          "powerId": "bard_t_legend",
          "powerName": "Legend",
          "level": 5
        },
        {
          "powerId": "bard_t_muse",
          "powerName": "Muse",
          "level": 5
        },
        {
          "powerId": "bard_t_thunderous_voice",
          "powerName": "Thunderous Voice",
          "level": 1
        },
        {
          "powerId": "bard_s_song_of_impunity",
          "powerName": "Song of Impunity",
          "level": 2
        }
      ]
    },
    "Cleric": {
      "className": "Cleric",
      "ruleSet": "caster",
      "tierMapping": [
        {
          "powerId": "cleric_s_blessing_from_wounds",
          "powerName": "Blessing From Wounds",
          "level": 1
        },
        {
          "powerId": "cleric_s_heal",
          "powerName": "Heal",
          "level": 1
        },
        {
          "powerId": "cleric_s_steal_life",
          "powerName": "Steal Life",
          "level": 1
        },
        {
          "powerId": "cleric_s_curse",
          "powerName": "Curse",
          "level": 1
        },
        {
          "powerId": "cleric_s_blessing_from_harm",
          "powerName": "Blessing From Harm",
          "level": 2
        },
        {
          "powerId": "cleric_s_create_zombie",
          "powerName": "Create Zombie",
          "level": 2
        },
        {
          "powerId": "cleric_s_cleanse",
          "powerName": "Cleanse",
          "level": 2
        },
        {
          "powerId": "cleric_s_inflict_wound",
          "powerName": "Inflict Wound",
          "level": 2
        },
        {
          "powerId": "cleric_s_banish",
          "powerName": "Banish",
          "level": 3
        },
        {
          "powerId": "cleric_s_create_vampire",
          "powerName": "Create Vampire",
          "level": 3
        },
        {
          "powerId": "cleric_a_adrenaline",
          "powerName": "Adrenaline",
          "level": 0
        },
        {
          "powerId": "cleric_s_resurrect",
          "powerName": "Resurrect",
          "level": 3
        },
        {
          "powerId": "cleric_s_greater_heal",
          "powerName": "Greater Heal",
          "level": 3
        },
        {
          "powerId": "cleric_s_create_lich",
          "powerName": "Create Lich",
          "level": 4
        },
        {
          "powerId": "cleric_s_mass_healing",
          "powerName": "Mass Healing",
          "level": 4
        },
        {
          "powerId": "cleric_s_phoenix_tears",
          "powerName": "Phoenix Tears",
          "level": 4
        },
        {
          "powerId": "cleric_s_shackle",
          "powerName": "Shackle",
          "level": 4
        },
        {
          "powerId": "cleric_t_necromancer",
          "powerName": "Necromancer",
          "level": 5
        },
        {
          "powerId": "cleric_t_priest",
          "powerName": "Priest",
          "level": 5
        },
        {
          "powerId": "cleric_t_beacon_of_souls",
          "powerName": "Beacon of Souls",
          "level": 1
        }
      ]
    },
    "Druid": {
      "className": "Druid",
      "ruleSet": "caster",
      "tierMapping": [
        {
          "powerId": "druid_s_attunement_to_fire",
          "powerName": "Attunement to Fire",
          "level": 1
        },
        {
          "powerId": "druid_s_heat_weapon",
          "powerName": "Heat Weapon",
          "level": 0
        },
        {
          "powerId": "druid_s_eagle_eye",
          "powerName": "Eagle Eye",
          "level": 1
        },
        {
          "powerId": "druid_s_entangle",
          "powerName": "Entangle",
          "level": 1
        },
        {
          "powerId": "druid_s_fire_bolt",
          "powerName": "Fire Bolt",
          "level": 1
        },
        {
          "powerId": "druid_s_attunement_to_water",
          "powerName": "Attunement to Water",
          "level": 2
        },
        {
          "powerId": "druid_s_heal_self",
          "powerName": "Heal Self",
          "level": 0
        },
        {
          "powerId": "druid_s_heat_armor",
          "powerName": "Heat Armor",
          "level": 2
        },
        {
          "powerId": "druid_s_mist_cloak",
          "powerName": "Mist Cloak",
          "level": 2
        },
        {
          "powerId": "druid_s_serpent_fangs",
          "powerName": "Serpent Fangs",
          "level": 2
        },
        {
          "powerId": "druid_s_attunement_to_earth",
          "powerName": "Attunement to Earth",
          "level": 3
        },
        {
          "powerId": "druid_s_bear_strength",
          "powerName": "Bear Strength",
          "level": 3
        },
        {
          "powerId": "druid_s_corrosion",
          "powerName": "Corrosion",
          "level": 3
        },
        {
          "powerId": "druid_s_turtle_shell",
          "powerName": "Turtle Shell",
          "level": 3
        },
        {
          "powerId": "druid_s_attunement_to_air",
          "powerName": "Attunement to Air",
          "level": 4
        },
        {
          "powerId": "druid_s_call_lightning",
          "powerName": "Call Lightning",
          "level": 4
        },
        {
          "powerId": "druid_t_missile_block",
          "powerName": "Missile Block",
          "level": 0
        },
        {
          "powerId": "druid_s_shove",
          "powerName": "Shove",
          "level": 0
        },
        {
          "powerId": "druid_s_wolf_pack",
          "powerName": "Wolf Pack",
          "level": 4
        },
        {
          "powerId": "druid_s_conduit",
          "powerName": "Conduit",
          "level": 4
        },
        {
          "powerId": "druid_t_avatar",
          "powerName": "Avatar",
          "level": 5
        },
        {
          "powerId": "druid_t_wild_heart",
          "powerName": "Wild Heart",
          "level": 5
        },
        {
          "powerId": "druid_t_wellspring",
          "powerName": "Wellspring",
          "level": 1
        }
      ]
    },
    "Fighter": {
      "className": "Fighter",
      "ruleSet": "martial",
      "tierMapping": [
        {
          "powerId": "fighter_t_light_armor",
          "powerName": "Light Armor",
          "level": 1
        },
        {
          "powerId": "fighter_a_scavenge",
          "powerName": "Scavenge",
          "level": 1
        },
        {
          "powerId": "fighter_a_repair",
          "powerName": "Repair",
          "level": 2
        },
        {
          "powerId": "fighter_a_shake_it_off",
          "powerName": "Shake It Off",
          "level": 2
        },
        {
          "powerId": "fighter_t_martial_feat",
          "powerName": "Martial Feat",
          "level": 3
        },
        {
          "powerId": "fighter_s_fire_bolt",
          "powerName": "Fire Bolt",
          "level": 0
        },
        {
          "powerId": "fighter_a_defy_death",
          "powerName": "Defy Death",
          "level": 3
        },
        {
          "powerId": "fighter_a_sunder",
          "powerName": "Sunder",
          "level": 4
        },
        {
          "powerId": "fighter_t_heavy_infantry",
          "powerName": "Heavy Infantry",
          "level": 5
        },
        {
          "powerId": "fighter_t_quartermaster",
          "powerName": "Quartermaster",
          "level": 5
        },
        {
          "powerId": "fighter_a_temper",
          "powerName": "Temper",
          "level": 0
        },
        {
          "powerId": "fighter_t_hold_the_gate",
          "powerName": "Hold the Gate",
          "level": 1
        }
      ]
    },
    "Monk": {
      "className": "Monk",
      "ruleSet": "martial",
      "tierMapping": [
        {
          "powerId": "monk_t_enlightened_soul",
          "powerName": "Enlightened Soul",
          "level": 1
        },
        {
          "powerId": "monk_t_missile_block",
          "powerName": "Missile Block",
          "level": 1
        },
        {
          "powerId": "monk_a_sanctuary",
          "powerName": "Sanctuary",
          "level": 2
        },
        {
          "powerId": "monk_s_heal_self",
          "powerName": "Heal Self",
          "level": 3
        },
        {
          "powerId": "monk_t_martial_feat",
          "powerName": "Martial Feat",
          "level": 3
        },
        {
          "powerId": "monk_s_fire_bolt",
          "powerName": "Fire Bolt",
          "level": 0
        },
        {
          "powerId": "monk_a_armistice",
          "powerName": "Armistice",
          "level": 4
        },
        {
          "powerId": "monk_t_dodge",
          "powerName": "Dodge",
          "level": 4
        },
        {
          "powerId": "monk_t_martial_artist",
          "powerName": "Martial Artist",
          "level": 5
        },
        {
          "powerId": "monk_t_warrior_monk",
          "powerName": "Warrior Monk",
          "level": 5
        },
        {
          "powerId": "monk_t_light_armor",
          "powerName": "Light Armor",
          "level": 0
        },
        {
          "powerId": "monk_t_swift_as_a_coursing_river",
          "powerName": "Swift as a Coursing River",
          "level": 1
        }
      ]
    },
    "Rogue": {
      "className": "Rogue",
      "ruleSet": "martial",
      "tierMapping": [
        {
          "powerId": "rogue_a_assassinate",
          "powerName": "Assassinate",
          "level": 1
        },
        {
          "powerId": "rogue_a_shadow_step",
          "powerName": "Shadow Step",
          "level": 1
        },
        {
          "powerId": "rogue_t_dodge",
          "powerName": "Dodge",
          "level": 2
        },
        {
          "powerId": "rogue_a_poison_blades",
          "powerName": "Poison Blades",
          "level": 2
        },
        {
          "powerId": "rogue_a_backstab",
          "powerName": "Backstab",
          "level": 3
        },
        {
          "powerId": "rogue_s_blink",
          "powerName": "Blink",
          "level": 3
        },
        {
          "powerId": "rogue_t_martial_feat",
          "powerName": "Martial Feat",
          "level": 3
        },
        {
          "powerId": "rogue_s_fire_bolt",
          "powerName": "Fire Bolt",
          "level": 0
        },
        {
          "powerId": "rogue_t_poison_projectiles",
          "powerName": "Poison Projectiles",
          "level": 4
        },
        {
          "powerId": "rogue_a_sabotage",
          "powerName": "Sabotage",
          "level": 4
        },
        {
          "powerId": "rogue_t_assassin",
          "powerName": "Assassin",
          "level": 5
        },
        {
          "powerId": "rogue_t_specter",
          "powerName": "Specter",
          "level": 5
        },
        {
          "powerId": "rogue_a_lethal_return",
          "powerName": "Lethal Return",
          "level": 0
        },
        {
          "powerId": "rogue_t_infiltration",
          "powerName": "Infiltration",
          "level": 1
        }
      ]
    },
    "Wizard": {
      "className": "Wizard",
      "ruleSet": "caster",
      "tierMapping": [
        {
          "powerId": "wizard_s_force_bolt",
          "powerName": "Force Bolt",
          "level": 1
        },
        {
          "powerId": "wizard_s_heat_weapon",
          "powerName": "Heat Weapon",
          "level": 1
        },
        {
          "powerId": "wizard_s_shove",
          "powerName": "Shove",
          "level": 1
        },
        {
          "powerId": "wizard_s_stasis",
          "powerName": "Stasis",
          "level": 1
        },
        {
          "powerId": "wizard_s_counterspell",
          "powerName": "Counterspell",
          "level": 2
        },
        {
          "powerId": "wizard_s_exile",
          "powerName": "Exile",
          "level": 2
        },
        {
          "powerId": "wizard_s_ice_ball",
          "powerName": "Ice Ball",
          "level": 2
        },
        {
          "powerId": "wizard_s_dispel_magic",
          "powerName": "Dispel Magic",
          "level": 2
        },
        {
          "powerId": "wizard_s_aegis",
          "powerName": "Aegis",
          "level": 3
        },
        {
          "powerId": "wizard_s_hold_person",
          "powerName": "Hold Person",
          "level": 3
        },
        {
          "powerId": "wizard_s_icy_blast",
          "powerName": "Icy Blast",
          "level": 3
        },
        {
          "powerId": "wizard_s_lightning_bolt",
          "powerName": "Lightning Bolt",
          "level": 3
        },
        {
          "powerId": "wizard_s_dragged_below",
          "powerName": "Dragged Below",
          "level": 4
        },
        {
          "powerId": "wizard_s_fire_ball",
          "powerName": "Fire Ball",
          "level": 4
        },
        {
          "powerId": "wizard_s_self_destruct",
          "powerName": "Self Destruct",
          "level": 4
        },
        {
          "powerId": "wizard_s_grimoire",
          "powerName": "Grimoire",
          "level": 4
        },
        {
          "powerId": "wizard_t_battlemage",
          "powerName": "Battlemage",
          "level": 5
        },
        {
          "powerId": "wizard_t_evoker",
          "powerName": "Evoker",
          "level": 5
        },
        {
          "powerId": "wizard_t_wizards_tower",
          "powerName": "Wizard's Tower",
          "level": 1
        }
      ]
    }
  }
};